# Generated by Django 5.2.5 on 2025-08-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
